name: "Deploy CloudFormation Stack"
on: 
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: mgenteluci/cloudformation-deploy-action@v1.4.0
      env:
        TEMPLATE: 'template.yml'
        AWS_STACK_NAME: 'my-simple-stack'
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_DEPLOY_BUCKET: sbt-bucket123
        AWS_BUCKET_PREFIX: stacks/pav
        PARAMETER_OVERRIDES: AliasName=prod
